export enum TARGET {
  UNIVERSAL = 'universal',
  GOOGLE_SEARCH = 'google_search',
  AMAZON = 'amazon',
  YOUTUBE_TRANSCRIPT = 'youtube_transcript',
  REDDIT_SUBDREDDIT = 'reddit_subreddit',
}

export const URL_TARGETS = [TARGET.UNIVERSAL, TARGET.AMAZON];
export const QUERY_TARGETS = [TARGET.GOOGLE_SEARCH];
export const HEADLESS_TARGETS = [TARGET.UNIVERSAL, TARGET.GOOGLE_SEARCH];
export const GEO_TARGETS = [
  TARGET.UNIVERSAL,
  TARGET.GOOGLE_SEARCH,
  TARGET.AMAZON,
  TARGET.YOUTUBE_TRANSCRIPT,
];
export const LOCALE_TARGETS = [TARGET.GOOGLE_SEARCH];
export const MARKDOWN_TARGETS = [TARGET.UNIVERSAL, TARGET.GOOGLE_SEARCH];
export const PARSE_TARGETS = [TARGET.GOOGLE_SEARCH, TARGET.AMAZON];
