export enum TARGET {
  UNIVERSAL = 'universal',
  GOOGLE_SEARCH = 'google_search',
  AMAZON = 'amazon',
}

export const URL_TARGETS = [TARGET.UNIVERSAL, TARGET.AMAZON];
export const QUERY_TARGETS = [TARGET.GOOGLE_SEARCH];
export const HEADLESS_TARGETS = [TARGET.UNIVERSAL, TARGET.GOOGLE_SEARCH];
export const MARKDOWN_TARGETS = [TARGET.UNIVERSAL, TARGET.GOOGLE_SEARCH];
export const PARSE_TARGETS = [TARGET.GOOGLE_SEARCH, TARGET.AMAZON];
